[2023-03-01T17:19:53.776+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.load_to_bq scheduled__2023-02-19T18:38:00+00:00 [queued]>
[2023-03-01T17:19:53.795+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.load_to_bq scheduled__2023-02-19T18:38:00+00:00 [queued]>
[2023-03-01T17:19:53.796+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-01T17:19:53.797+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-01T17:19:53.798+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-01T17:19:53.828+0000] {taskinstance.py:1300} INFO - Executing <Task(GCSToBigQueryOperator): load_to_bq> on 2023-02-19 18:38:00+00:00
[2023-03-01T17:19:53.834+0000] {standard_task_runner.py:55} INFO - Started process 998 to run task
[2023-03-01T17:19:53.842+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'update-filter', 'load_to_bq', 'scheduled__2023-02-19T18:38:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/update-filter.py', '--cfg-path', '/tmp/tmpm7h4whg4']
[2023-03-01T17:19:53.844+0000] {standard_task_runner.py:83} INFO - Job 121: Subtask load_to_bq
[2023-03-01T17:19:53.936+0000] {task_command.py:388} INFO - Running <TaskInstance: update-filter.load_to_bq scheduled__2023-02-19T18:38:00+00:00 [running]> on host 65ef354bad49
[2023-03-01T17:19:54.002+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update-filter
AIRFLOW_CTX_TASK_ID=load_to_bq
AIRFLOW_CTX_EXECUTION_DATE=2023-02-19T18:38:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-19T18:38:00+00:00
[2023-03-01T17:19:54.012+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-01T17:19:54.013+0000] {gcs_to_bigquery.py:377} INFO - Using existing BigQuery table for storing data...
[2023-03-01T17:19:54.058+0000] {gcs_to_bigquery.py:381} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': '***-gcs-bq', 'datasetId': '***_dataset', 'tableId': 'upload'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://***-gcs-bq/update.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'id', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'name', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'age', 'type': 'INTEGER', 'mode': 'REQUIRED'}]}, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-03-01T17:19:54.060+0000] {bigquery.py:1542} INFO - Inserting job ***_update_filter_load_to_bq_2023_02_19T18_38_00_00_00_a2e4324cb95593b2fa28bcc0c4b61e6f
[2023-03-01T17:19:55.271+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 440, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.Forbidden: 403 Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas
[2023-03-01T17:19:55.280+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=update-filter, task_id=load_to_bq, execution_date=20230219T183800, start_date=20230301T171953, end_date=20230301T171955
[2023-03-01T17:19:55.289+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 121 for task load_to_bq (403 Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas; 998)
[2023-03-01T17:19:55.346+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-01T17:19:55.373+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
